services:
  db:
    image: dollysarmiento2024/mi_bbdd_cine:v1
    container_name: contenedor_bbdd_cine
    #environment:
    #  MYSQL_ROOT_PASSWORD: fernanda
    #  MYSQL_DATABASE: cine
    #  MYSQL_USER: fernanda
    #  MYSQL_PASSWORD: fernanda
    ports:
      - "3306:3306"
  php:
    image: dollysarmiento2024/mi_app_cine:v1
    container_name: contenedor_app_cine
    ports:
      - "8080:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedor_php_myadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: fernanda
    ports:
      - "8081:80"
    depends_on:
      - db